@baseUrl = http://localhost:3000


##################################################
### Auth
##################################################

POST {{baseUrl}}/api/auth/sign-up
Content-Type: application/json

{
  "name": "Willian Lima",
  "email": "willian@email.com",
  "password": "123456"
}

###

### Sign in with email and password
# @name login
POST {{baseUrl}}/api/auth/sign-in/email-password
Content-Type: application/json

{
  "email": "alan@email.com",
  "password": "123456"
}

###

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NjE0MzAzNDEsImV4cCI6MTc2MTUxNjc0MSwic3ViIjoie1widXNlcklkXCI6XCIwMTlhMWQ2ZS0wODU3LTc3MzEtYjVjNy05MzFiYmU5ZTk2MDNcIn0ifQ.aBw10uXS7YskkfM8But9Nca-rUF9tRN8CU2vs1it6sE
# @authToken = {{login.response.body.token}}

### Get user session
GET {{baseUrl}}/api/auth/me
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

### Complete first login
POST {{baseUrl}}/api/auth/complete-first-login
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

##################################################
### Memory
##################################################

# Get memory list
GET {{baseUrl}}/api/memory
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# List memories planss
GET {{baseUrl}}/api/memory/plan
Content-Type: application/json
Authorization: Bearer {{authToken}}

###


# Init memory
POST {{baseUrl}}/api/memory/init
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# List memories
GET {{baseUrl}}/api/memory
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# Create a memory plan
POST {{baseUrl}}/api/memory/plan
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Plano Pro",
  "description": "Até 10.000 fotos e 1.000 vídeos",
  "currencyCode": "BRL",
  "priceCents": 1990,
  "photosLimit": 10000,
  "videosLimit": 1000,
  "position": 3
}

# {
#   "name": "Plano Pro",
#   "description": "Até 5.000 fotos e 500 vídeos",
#   "currencyCode": "BRL",
#   "priceCents": 1990,
#   "photosLimit": 5000,
#   "videosLimit": 500,
#   "position": 1
# }

###

# List memory plans
GET {{baseUrl}}/api/memory/plan
Content-Type: application/json
Authorization: Bearer {{authToken}}


