version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "story_keep"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    healthcheck:
      test: "exit 0"
    ports:
      - "3307:3306"
    expose:
      - "3306"

  story-keep-api-integration:
    container_name: story-keep-api
    build:
      context: .
      dockerfile: dockerfile.test
    ports:
      - 3001:80
    environment:
      - NODE_ENV=test
      - PORT=80
      - JWT_SECRET=vwei75vsib&tSA!
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=story_keep
      - MYSQL_PORT=3306
      - READ_MEDIA_EXPIRES_IN=3600
      - R2_STORAGE_ACCESS_KEY_ID=123
      - R2_STORAGE_SECRET_ACCESS_KEY=123
      - STRIPE_SECRET_KEY=123
      - STRIPE_ENDPOINT_SECRET=123
      - GOOGLE_CLIENT_ID=123
      - GOOGLE_CLIENT_SECRET=123
    depends_on:
      mysql:
        condition: service_healthy
    stdin_open: true
    tty: true
